### ISSUE TITLE
Publish date in the list of posts

### ISSUE THREAD

**Issue by balaramadurai** [masasam/emacs-easy-hugo#45]
Hello @masasam, 
  Thanks for the wonderful package easy-hugo. 

I have a feature request to make:
Listing the publishing date of the posts in the list (#39 dealt with sorting, however a listing would also help, I think)

Thanks again for your wonderful work
Have a good day!
Bala

**Comment by masasam** [comment]
Hi @balaramadurai .
Thank you for comment.
I think it is a good feature request.
But there is a reason why it can not be implemented.
The reason is that display becomes slow if there are a lot of files.
It is also why org-mode users can not use easy-hugo because org-mode can not handle display publish time.

**Comment by balaramadurai** [comment]
Fair enough. Thanks @masasam 

Have a good day!
