### ISSUE TITLE
Unable to see post files if they are under subdirs?

### ISSUE THREAD

**Issue by xuhdev** [masasam/emacs-easy-hugo#81]
If posts are under subdirs of the post dir, seems like there's no way to see them in the `easy-hugo` buffer:

```
content/
  post/
    _index.md
    2024/
      post-1/index.md
      post-2/index.md
```

The next/prev post feature works as expected.

**Comment by masasam** [comment]
Hi @xuhdev !
Thank you for comment.
I don't understand what you mean, so please explain it a little more clearly.

**Comment by xuhdev** [comment]
I've created a minimal example https://github.com/xuhdev/easy-hugo-issue-81

1. Clone the repo along with its submodules: `git clone --recursive https://github.com/xuhdev/easy-hugo-issue-81`.
2. Points `easy-hugo-basedir` to the cloned repo.
3. Run `easy-hugo` from within Emacs.

The buffer shows no post, despite that there are posts under `content/post`.

![image](https://github.com/user-attachments/assets/7ac86bc3-38cc-4d2d-93a1-2d297259da97)

**Comment by masasam** [comment]
I understand the situation. thank you!
This is by design.
easy-hugo is not display anything if there are only folders in the post directory.
Show only files in post directory.
The design is to move with Pre postdir(,) or Next postdir(.) and post article with (n).
You can also move it using easy-hugo-postdir.

![Screenshot From 2024-11-01 13-28-44](https://github.com/user-attachments/assets/b71e6435-fe3e-4df7-b5ae-af3ce396e995)

**Comment by xuhdev** [comment]
Thanks! Now I got how it works!
